# -*- mode: ruby -*-                      #현재 파일 ruby 언어를 사용
# vi: set ft=ruby :                       #ft: file type 
# 가능한 ansible-nodes 를 먼저 만들고 마지막에 ansible-server 만들는게 좋음 

#================#
# CentOS Nodes #
#================#
#Ansible-Node01
Vagrant.configure("2") do |config|          
  config.vm.boot_timeout = 1800             # 30분 제한 시간                     
  config.vm.define "ansible-node01" do |cfg|
    cfg.vm.box = "centos/7"                                    
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Node01"                                
  end
    cfg.vm.host_name = "ansible-node01"                         
    cfg.vm.network "private_network", ip: "192.168.56.11"       
    cfg.vm.network "forwarded_port", guest: 22, host: 60011, auto_correct: true, id: "ssh"       
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", path: "bash_ssh_conf_4_CentOS.sh"
  end
end

#Ansible-Node02
Vagrant.configure("2") do |config|                      
  config.vm.boot_timeout = 1800             # 30분 제한 시간                     
  config.vm.define "ansible-node02" do |cfg|
    cfg.vm.box = "centos/7"                                    
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Node02"                                
  end
    cfg.vm.host_name = "ansible-node02"   
    cfg.vm.network "private_network", ip: "192.168.56.12"       
    cfg.vm.network "forwarded_port", guest: 22, host: 60012, auto_correct: true, id: "ssh"       
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", path: "bash_ssh_conf_4_CentOS.sh"
  end
end

#Ansible-Node03
Vagrant.configure("2") do |config|                    
  config.vm.boot_timeout = 1800             # 30분 제한 시간                     
  config.vm.define "ansible-node03" do |cfg|
    cfg.vm.box = "centos/7"                                    
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Node03"                                
  end
    cfg.vm.host_name = "ansible-node03"                         
    cfg.vm.network "private_network", ip: "192.168.56.13"       
    cfg.vm.network "forwarded_port", guest: 22, host: 60013, auto_correct: true, id: "ssh"       
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", path: "bash_ssh_conf_4_CentOS.sh"
  end
end


#================#
# Ansible Server #
#================#

Vagrant.configure("2") do |config|                              
  config.vm.define "ansible-server" do |cfg|
    cfg.vm.box = "centos/7"                                    
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "Ansible-Server"                                
  end
    cfg.vm.host_name = "ansible-server"                         
    cfg.vm.network "private_network", ip: "192.168.56.10"       
    cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"       
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", inline: "yum install epel-release -y"
    cfg.vm.provision "shell", inline: "yum install ansible -y"      
    cfg.vm.provision "file", source: "ansible_env_ready.yml", destination: "ansible_env_ready.yml"
    cfg.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
  end
end
